sudo: required

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - ./create_stack.sh -r https://github.com/laravel/laravel

script:
  - ./artisan.sh migrate:fresh
